// examples/mobx-flux-react-example/src/todo/ui/todo-list.tsx
import {observer} from "mobx-react-lite";
import {useAppDispatch, useAppSelector} from "../../store";
import {TodoCard} from "./todo-card.tsx";
import {useCallback, useEffect} from "react";
import {deleteTodo, toggleTodo} from "../model";
import {fetchTodoList} from "../api";

export const TodoList = observer(() => {
    
    const dispatch = useAppDispatch()

    const {todos, loading, error} = useAppSelector(state => state.todo)

    const handleDelete = useCallback((id: number) => {
        dispatch(deleteTodo(id))
    }, [dispatch])

    const handleToggle = useCallback((id: number) => {
        dispatch(toggleTodo(id))
    }, [dispatch])

    useEffect(() => {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        dispatch(fetchTodoList())
    }, [dispatch])

    if(loading){
        return <div>Loading...</div>
    }

    if(error){
        return <div>Oops {error} :(</div>
    }

    return (
        <div className='todo_list'>
            <ul>
                {
                    todos.map(todo => (
                        <TodoCard
                            key={todo.id}
                            todo={todo}
                            onDelete={handleDelete}
                            onToggleComplete={handleToggle}
                        />
                    ))
                }
            </ul>
        </div>
    );
});

// examples/mobx-flux-vue-example/src/todo/todo-list.vue
<script setup lang="ts">

import {onMounted} from "vue";
import {Observer} from "mobx-vue-lite";

import TodoCard from "./todo-card.vue";
import {useAppDispatch, useAppSelector} from "../store";
import {fetchTodoList} from "./todo-api.ts";
import {deleteTodo, toggleTodo} from "./todo-store.ts";

const dispatch = useAppDispatch()

const handleToggle = (id: number) => {
  dispatch(toggleTodo(id))
}

const handleDelete = (id: number) => {
  dispatch(deleteTodo(id))
}

const todos = useAppSelector(state => state.todo)

onMounted(() => {
  // @ts-ignore
  dispatch(fetchTodoList());
})

</script>


<template>
  <Observer>
   <ul class="todo_list">
     <li v-for="todo in todos.todos" :key="todo.id">
       <TodoCard :on-delete="handleDelete" :on-toggle-complete="handleToggle" :todo="todo"/>
     </li>
   </ul>
  </Observer>
</template>


<style @global>

.todo_list{
  background: #fff;
  box-shadow: 0 0 27px #ccc;
  max-width: 1200px;
  width: 100%;
  padding: 0 20px;
  margin: 0 auto;
}

.todo_list ul {
  list-style: none;
  padding: 0;
}
</style>
