// examples/mobx-flux-react-example/src/todo/ui/todo-card.tsx
import {observer} from "mobx-react-lite";
import {ITodo} from "../api";
import './style.css';
import {useCallback, MouseEvent} from "react";
import {DeleteButton} from "../../components";

interface ITodoCardProps {
    todo: ITodo;
    onDelete: (id: number) => void;
    onToggleComplete: (id: number) => void;
}

export const TodoCard = observer(({todo, onDelete, onToggleComplete}: ITodoCardProps) => {

    const handleToggle = useCallback(() => {
        onToggleComplete(todo.id)
    }, [onToggleComplete, todo.id])

    const handleDelete = useCallback((e: MouseEvent<HTMLButtonElement>) => {
        e.stopPropagation()
        onDelete(todo.id)
    }, [onDelete, todo.id])

    return (
        <li>
            <label>
                <input
                    type="checkbox"
                    className="hidden_real_check"
                    checked={todo.completed}
                    onChange={handleToggle}
                />
                <div className="todo_element">
                        <DeleteButton className='deleteButton' onClick={handleDelete}/>
						<span className="customized_ckeck">
							<span className="checkbox">
								<span className='internal_one'></span>
								<span className='internal_two'></span>
							</span>
						</span>
                    <span className="element_title">{todo.title}</span>
                </div>
            </label>
        </li>
    );
});

// examples/mobx-flux-vue-example/src/todo/todo-card.vue
<script setup lang="ts">
import {Observer} from "mobx-vue-lite";

import {ITodo} from "./todo-api";

interface Props {
  todo: ITodo,
  onDelete: (id: number) => void;
  onToggleComplete: (id: number) => void;
}

const {todo, onToggleComplete, onDelete} = defineProps<Props>()

console.log('todo => ', todo)

const handleToggle = () => {
  onToggleComplete(todo.id)
}

const handleDelete = () => {
  onDelete(todo.id)
}

</script>

<template>
  <Observer>
    <li>
      <label>
        <input
            type="checkbox"
            class="hidden_real_check"
            @checked="todo.completed"
            @change="handleToggle"
        />
        <div class="todo_element">
          <button class='deleteButton' @click="handleDelete">
            Delete
          </button>
          <span class="customized_ckeck">
							<span class="checkbox">
								<span class='internal_one'></span>
								<span class='internal_two'></span>
							</span>
						</span>
          <span class="element_title">{{todo.title}}</span>
        </div>
      </label>
    </li>
  </Observer>
</template>
